#!/bin/bash
set +o noclobber
grpnum=$(awk -F: '$1 == "'$1'" {print $4}' /etc/passwd)
awk -F: '$4 =='$grpnum' {print  $1}' /etc/passwd\
| sort > grplist 
who | awk '{print $1}' | sort > loglist \
| comm -12 - grplist 
rm grplist 
