#!/bin/bash
leave=no
while [ $leave = no ]
do
clear
cat <<++
MAIN MENU
1)    Print current working directory
2)    List all files in current directory
3)    Print today's date and time
x)    exit
++
echo Please enter your selection $USER:
read selection
case $selection in
1) pwd ;;
2) ls -l ;;
3) date ;;
q|Q|e|E|x|X) leave=yes ;;
*) echo "Invalid choice. Try again.";;
esac
echo -n "Press Enter to continue "
read hold
done
exit 0
