#!/bin/bash
cat <<++
MAIN MENU
1)    Print current working directory
2)    List all files in current directory
3)    Print today's date and time
++
echo Please enter your selection $USER:
read selection
echo Your selection was $selection
